sudo: false
language: node_js
env:
  - CLI_TIMEOUT=10000
node_js:
  - "8"
  - "lts/*"
  - "stable"
before_script:
  - git clone --depth=50 --branch=extends https://github.com/shexSpec/shexTest.git ../shexTest
  - cat packages/shex-core/lib/ShExUtil.js
script:
  - npm run test-all
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
