blank_issues_enabled: true
contact_links:
  - name: ShEx test suite
    url: https://github.com/shexSpec/shexTest
    about: ShEx conformance tests

  - name: ShEx language
    url: https://github.com/shexSpec/shex
    about: ShEx language features and behavior

  - name: ShEx specification
    url: https://github.com/shexSpec/spec
    about: Suggestions for improving the ShEx specification
